### ISSUE TITLE
[FR]: Movies by Genres

### ISSUE THREAD

**Issue by hadi-norouzi** [moallemi/Film-Time#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Related app

All - Android

### Describe the problem

I need to click on genre in movie/show detail page and get list of movies/shows by that genre.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by moallemi** [comment]
You can work on this. Please check **if** we can reuse the `video-thumbnail-grid` module.

**Comment by hadi-norouzi** [comment]
```video-thumbnail-grid``` takes two params, ```VideoType``` and ```VideoListType```.
Do you think it's ok to add another param for genre? or add another module only for genre grid?

**Comment by moallemi** [comment]
No. Just make this `VideoThumbnailGridScreen` (Line: 55) public and use it with your new view model in a new module:

```kotlin
@Composable
private fun VideoThumbnailGridScreen(
  state: VideoThumbnailGridUiState,
  pagedList: LazyPagingItems<VideoThumbnail>,
  onMovieClick: (tmdbId: Int) -> Unit,
  onShowClick: (tmdbId: Int) -> Unit,
  onBack: () -> Unit,
)
```
