### ISSUE TITLE
[FR]: List Trailers For Movies and Shows

### ISSUE THREAD

**Issue by moallemi** [moallemi/Film-Time#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Related app

Mobile - Android

### Describe the problem

List Trailers For Movies and Shows.
- Using TMDB API.
- Link to Youtube for playing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hadi-norouzi** [comment]
@moallemi Can i work on this?
