### ISSUE TITLE
Add a screen for displaying all trending Movies

### ISSUE THREAD

**Issue by moallemi** [moallemi/Film-Time#11]
As a movie enthusiast,
I want to browse a screen dedicated to trending movies displayed in a grid format with endless pagination
so that I can continuously discover and explore the most popular movies without interruptions.

**Acceptance Criteria:**

1. The trending movies screen should be easily accessible from home sections with a "More" button.
2. Movies should be displayed as thumbnails in a grid format.
4. Upon scrolling to the bottom of the list, the next set of trending movies should automatically load (endless pagination).
5. There should be a visual indication (e.g., loading spinner) while new movies are being fetched.
6. In case of a network error or no more trending movies available, an appropriate message should be displayed to the user.
7. Tapping on a movie thumbnail should take the user to the detailed movie description screen.

Feel Free to create separate PRs to implement this story

**Comment by u3frajaeian** [comment]
I started working on it.🖐️

**Comment by vyom198** [comment]
i am working on this issue

**Comment by Sobhan-mp** [comment]
Hi, I'm starting to working on it! 
I guess I will create a pr in a couple of days from now!

**Comment by moallemi** [comment]
@Sobhan-mp Thanks
