### ISSUE TITLE
Add a screen for displaying all trending Shows

### ISSUE THREAD

**Issue by moallemi** [moallemi/Film-Time#12]
As a series enthusiast,
I want to browse a screen dedicated to trending shows displayed in a grid format with endless pagination
so that I can continuously discover and explore the most popular shows without interruptions.

**Acceptance Criteria:**

1. The trending shows screen should be easily accessible from home sections with a "More" button.
2. Shows should be displayed as thumbnails in a grid format.
4. Upon scrolling to the bottom of the list, the next set of trending shows should automatically load (endless pagination).
5. There should be a visual indication (e.g., loading spinner) while new shows are being fetched.
6. In case of a network error or no more trending shows available, an appropriate message should be displayed to the user.
7. Tapping on a shows thumbnail should take the user to the detailed shows description screen.

Feel free to create separate PRs to implement this story

**Comment by u3frajaeian** [comment]
I started working on it.🖐️
