### ISSUE TITLE
Home Screen Error Handling

### ISSUE THREAD

**Issue by moallemi** [moallemi/Film-Time#13]
As a movie streaming app user,
I want to be informed of any internet connectivity or API issues when accessing the home screen,
so that I understand why content might not be loading and can take appropriate action.

1. If there's no internet connection, a clear message should be displayed stating "No internet connection. Please check your network settings."
2. If the app's API fails to load data, a message should be displayed stating "Oops! Something went wrong. Please try again later."
3. The user should have the option to retry fetching data with a "Retry" button or action.
4. There should be an icon or visual cue accompanying the error message to quickly indicate the type of issue (e.g., a disconnected plug icon for internet issues).
5. If possible, previously loaded data (if any) should still be displayed or cached to allow users to access some content even if the API fails momentarily.
6. The rest of the UI should remain responsive and accessible even if there's an error on the home screen content.
7. Error messages should be brief but clear, avoiding technical jargon to ensure all users understand the issue.

**Comment by vyom198** [comment]
i am working on this issue

**Comment by vyom198** [comment]
I am using Room for data caching, but I believe that Room does not support KAPT with Kotlin 1.9.10
<img width="813" alt="image" src="https://github.com/moallemi/Film-Time/assets/112750331/f497c3b2-6649-4f21-a37c-a6db2148fa99">

**Comment by moallemi** [comment]
@vyom198 If you decided to use room based on AC 5, We do not need to use room (and data caching by its means) for this issue. 

> AC 5: If possible, previously loaded data (if any) should still be displayed or cached to allow users to access some content even if the API fails momentarily.

Just display errors based on error types and we will handle data caching later.
