### ISSUE TITLE
Movie Detail Screen error handling

### ISSUE THREAD

**Issue by moallemi** [moallemi/Film-Time#14]
As a movie streaming app user,
I want to be informed of any internet connectivity or API issues when accessing the movie detail screen,
so that I understand why content might not be loading and can take appropriate action.

If there's no internet connection, a clear message should be displayed stating "No internet connection. Please check your network settings."
If the app's API fails to load data, a message should be displayed stating "Oops! Something went wrong. Please try again later."
The user should have the option to retry fetching data with a "Retry" button or action.
There should be an icon or visual cue accompanying the error message to quickly indicate the type of issue (e.g., a disconnected plug icon for internet issues).
If possible, previously loaded data (if any) should still be displayed or cached to allow users to access some content even if the API fails momentarily.
The rest of the UI should remain responsive and accessible even if there's an error on the movie detail screen content.
Error messages should be brief but clear, avoiding technical jargon to ensure all users understand the issue.

**Comment by Kardelio** [comment]
If this ticket is still avaialble id love to jump on this and give it a go, if thats ok?

**Comment by moallemi** [comment]
Yes, please go on! 👌

**Comment by Kardelio** [comment]
awesome thank you! could you assign me to this issue please? <3

**Comment by moallemi** [comment]
Hey @Kardelio 

Are you still working on this user story? Because due to a [misunderstanding](https://github.com/moallemi/Film-Time/issues/15#issuecomment-1755066872) @u3frajaeian created a [PR](https://github.com/moallemi/Film-Time/pull/19) for this user story.

**Comment by Kardelio** [comment]
Hey sorry for the delay respone!
No no im not working on this, so all good go ahead with the PR mentioned above! Thanks for reaching out though!

**Comment by moallemi** [comment]
Done via #21
