### ISSUE TITLE
Show Detail Screen error handling

### ISSUE THREAD

**Issue by moallemi** [moallemi/Film-Time#15]
As a movie streaming app user,
I want to be informed of any internet connectivity or API issues when accessing the show details screen,
so that I understand why content might not be loading and can take appropriate action.

If there's no internet connection, a clear message should be displayed stating "No internet connection. Please check your network settings."
If the app's API fails to load data, a message should be displayed stating "Oops! Something went wrong. Please try again later."
The user should have the option to retry fetching data with a "Retry" button or action.
There should be an icon or visual cue accompanying the error message to quickly indicate the type of issue (e.g., a disconnected plug icon for internet issues).
If possible, previously loaded data (if any) should still be displayed or cached to allow users to access some content even if the API fails momentarily.
The rest of the UI should remain responsive and accessible even if there's an error on the show details screen content.
Error messages should be brief but clear, avoiding technical jargon to ensure all users understand the issue.

**Comment by u3frajaeian** [comment]
I started working on it.🖐️

**Comment by u3frajaeian** [comment]
Hi there,

I misunderstood the issue, and I have implemented error handling in the movie detail screen. I am confident that I can also implement error handling for the show detail screen to ensure consistency in both detail screens.

**Comment by moallemi** [comment]
@u3frajaeian No problem. We will continue with your PR. Please create another PR for show detail screen after we merged this one

**Comment by u3frajaeian** [comment]
@moallemi Ok for sure.

**Comment by moallemi** [comment]
Done via #21
