### ISSUE TITLE
Sync with Trakt

### ISSUE THREAD

**Issue by moallemi** [moallemi/Film-Time#16]
As a movie and TV show enthusiast,
I want to sync my viewing activity with Trakt 
so that I can keep track of movies and episodes I've watched and manage my viewing history seamlessly.

**Acceptance Criteria:**

1. Users should be able to link their Trakt account from within the app (icon in home toolbar)
2. When viewing a movie or episode detail page, there should be a clear indicator showing whether the content has been marked as watched on Trakt.
3. If the movie or episode has already been marked as watched on Trakt, a button labeled "Mark as Unwatched" should be visible.
4. If the movie or episode has not been marked as watched on Trakt, a button labeled "Mark as Watched" should be displayed.
5. Tapping the "Mark as Watched" button should immediately update the Trakt account and reflect the change within the app.
6. Tapping the "Mark as Unwatched" button should reverse the action, updating both Trakt and the app's interface.
7. In the event of a sync issue or failure with Trakt, a clear error message should be displayed to the user, indicating the problem.
8. Any changes made within the app (marking as watched/unwatched) should be reflected in real-time on the user's Trakt account.

Feel free to create separate PRs for this user story

**Comment by hadi-norouzi** [comment]
I started working on it.🖐️

**Comment by hadi-norouzi** [comment]
I implemented login with trakt but I faced some issues.
First of all, we use tmdb for trending movies and shows, they are not from trakt and we do not access movie or show IDs from trakt.
My suggestion is to add trakt APIs like those we have for tmdb and fill ```traktId``` filed after that we can use that id for trakt API.
Or we could replace tmdb trending movie and shows with trakt trendings, trakt has tmdb IDs in each movie or show objects. 

what is your suggestion?

**Comment by moallemi** [comment]
We could consider switching to the Trakt API for all details and lists. I remember using TraktAPI in another project, but I can't recall why I eventually chose TMDB for default.

So I recommend using [Trakt ID lookup API](https://trakt.docs.apiary.io/#reference/search/id-lookup/get-id-lookup-results) to get IDs and fill our data:

<img src="https://github.com/moallemi/Film-Time/assets/1250691/e11102b1-53d8-4db0-92f0-dc73d8932315" width="70%" />

**Comment by hadi-norouzi** [comment]
I have just confused a little bit. 
For now, change TmdbApi to TraktApi or request each row with TraktApi to get Trakt ID for each item?

**Comment by vyom198** [comment]
> I have just confused a little bit. For now, change TmdbApi to TraktApi or request each row with TraktApi to get Trakt ID for each item?

not related to issue , should i have to get new api key from the website because the api key is null in buildconfig class? and when i run the project the mainactivity shows blank screen

**Comment by moallemi** [comment]
> I have just confused a little bit. For now, change TmdbApi to TraktApi or request each row with TraktApi to get Trakt ID for each item?

@hadi-norouzi In order to optimize our API calls and ensure efficient performance, I recommend fetching the traktId specifically on the movie/show details screen. This approach ensures that we only retrieve the traktId when it's essential, which is in the detailed screens where we display the watched/unwatched status. By doing so, we can minimize the number of unnecessary API calls to Trakt.

So, when we load movie details from TMDB, we can initiate an asynchronous call to Trakt to obtain the traktId. Once we have that, we can seamlessly fetch the watch/unwatched status and continue with the rest of the required implementation.

**Comment by moallemi** [comment]
> not related to issue , should i have to get new api key from the website because the api key is null in buildconfig class? and when i run the project the mainactivity shows blank screen

@vyom198 I Added a section to [README](https://github.com/moallemi/Film-Time/blob/dev/README.md#api-keys) file and described how to gain API keys
