### ISSUE TITLE
Blank White Screen

### ISSUE THREAD

**Issue by ashutoshkailkhura** [moallemi/Film-Time#29]
Hi
I am Unable to preview app, after storing my API key in environment variable , show shimmer animation for few sec then getting blank screen, their is no error on Log-cat also 

Running on 
Android Studio Hedgehog
Linux Mint 20.3

**Comment by moallemi** [comment]
Right now we do not have error handling on Home screen. that's why you see blank screen.
There is an open issue #20 for that. For now you should debug and find the error.
