### ISSUE TITLE
[FR]: Beautify the Movie/Shows Detail page

### ISSUE THREAD

**Issue by u3frajaeian** [moallemi/Film-Time#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Related app

Mobile - Android

### Describe the problem

I want to change the detail page beautify it and add some sections, like similar, caster, director, etc...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by moallemi** [comment]
Movie Detail Screen via #51
