### ISSUE TITLE
Settings Screen

### ISSUE THREAD

**Issue by moallemi** [moallemi/Film-Time#50]
- [ ] Trakt Login Status
- [ ] Theme selector? 🤔

**Comment by u3frajaeian** [comment]
Hello, I am capable of completing the task, but in order to do so effectively, I require additional information. Could you please provide me with more details or insights to guide my understanding and approach?

**Comment by moallemi** [comment]
> Hello, I am capable of completing the task, but in order to do so effectively, I require additional information. Could you please provide me with more details or insights to guide my understanding and approach?

Currently, I don't have a solid design or functionality in mind for the settings screen except for Trakt login status. However, I'm eager to hear your suggestions and insights.

<img width=50% src="https://github.com/moallemi/Film-Time/assets/1250691/9962d39e-e803-4b83-9c3f-d4886734d186" />
