### ISSUE TITLE
beautify detail page (in Series)

### ISSUE THREAD

**Issue by u3frajaeian** [moallemi/Film-Time#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Related app

Mobile - Android

### Describe the problem

beautify series detail screen and add cast and similar section

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by moallemi** [comment]
Hi @u3frajaeian.

That would be great. Let's do it 💪.

A few notes:
While you are enhancing shows detail screen, check if we can reuse any UI sections from movie detail screen, e.g. I remember you created a cast/crew components, maybe we can move `CreditRowItem` composable to core:ui module to reuse it here.

**Comment by moallemi** [comment]
Done via 5557fe563cc677da2b449781913370dca7a70650
