### ISSUE TITLE
[FR]: Implement Tv Shows detail, Seasons and Episodes

### ISSUE THREAD

**Issue by hadi-norouzi** [moallemi/Film-Time#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Related app

All - Android

### Describe the problem

Show episodes and seasons for TvShows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by moallemi** [comment]
Dear @hadi-norouzi, @u3frajaeian Is working on shows detail screen #62. Let's wait until he finishes his part. Then we can discuss on details

**Comment by u3frajaeian** [comment]
Hi, #64  PR has been sent.
Now @hadi-norouzi or I can implement this feature.
