### ISSUE TITLE
[FR]: Search movie by keyword

### ISSUE THREAD

**Issue by hadi-norouzi** [moallemi/Film-Time#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Related app

All - Android

### Describe the problem

As a user, I want to have a search functionality in the movies section or somewhere in the app.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by moallemi** [comment]
I would suggest adding only one screen for search and display all search results in one place (for now: Movies and shows. Later we can display actors and episodes as well)

**Comment by hadi-norouzi** [comment]
> I would suggest adding only one screen for search and display all search results in one place (for now: Movies and shows. Later we can display actors and episodes as well)
> 
> 
> 
> 

So do you think I should add a tab in home?

**Comment by hadi-norouzi** [comment]
> Yes, That would be great. And what do you think of this sketch?
> 
> 
> 
> ![IMG_2414](https://github.com/moallemi/Film-Time/assets/1250691/ebfa3fa8-95cb-4309-8d2b-52eddd6f8ff2)
> 
> 

It is great. I will do it.

**Comment by hadi-norouzi** [comment]
> > Yes, That would be great. And what do you think of this sketch?
> > ![IMG_2414](https://private-user-images.githubusercontent.com/1250691/331824740-ebfa3fa8-95cb-4309-8d2b-52eddd6f8ff2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMzYxMjAsIm5iZiI6MTcxNjEzNTgyMCwicGF0aCI6Ii8xMjUwNjkxLzMzMTgyNDc0MC1lYmZhM2ZhOC05NWNiLTQzMDktOGQyYi01MmVkZGQ2ZjhmZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTlUMTYyMzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzI1YzU3NDI4NzUzNGQyZjJjZGY0NzAwOTI4MzYxYTgyZDU3YWQzNmVkYjhmMDE1NDdiZTM0ZTMyMmY3MjAwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.s2QkxIbylfJh6l2noYR6dHXJKUjpjcD7JuTj6qw4-2k)
> 
> It is great. I will do it.
Hi Mr. @moallemi.
```TMDB``` has three API for search, movie, tv shows and multi search.
In multi search API it gives me dynamic list of movie or show or person (actor).
what would you suggest to parse these dynamic data? it must be handled in API layer or datasource layer?
It's better to have another response parser for it or just return ```Any``` type and handle this mapping inside datasource?

**Comment by hadi-norouzi** [comment]
> Yes, That would be great. And what do you think of this sketch?
> 
> ![IMG_2414](https://private-user-images.githubusercontent.com/1250691/331824740-ebfa3fa8-95cb-4309-8d2b-52eddd6f8ff2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMzYxMjAsIm5iZiI6MTcxNjEzNTgyMCwicGF0aCI6Ii8xMjUwNjkxLzMzMTgyNDc0MC1lYmZhM2ZhOC05NWNiLTQzMDktOGQyYi01MmVkZGQ2ZjhmZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTlUMTYyMzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzI1YzU3NDI4NzUzNGQyZjJjZGY0NzAwOTI4MzYxYTgyZDU3YWQzNmVkYjhmMDE1NDdiZTM0ZTMyMmY3MjAwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.s2QkxIbylfJh6l2noYR6dHXJKUjpjcD7JuTj6qw4-2k)

Hi Mr. @moallemi.
TMDB has three API for search, movie, tv shows and multi search.
In multi search API it gives me dynamic list of movie or show or person (actor).
what would you suggest to parse these dynamic data? it must be handled in API layer or datasource layer?
It's better to have another response parser for it or just return Any type and handle this mapping inside datasource?

**Comment by moallemi** [comment]
Dear @hadi-norouzi,

I'd suggest adding a separate search everywhere:
1. In `:data:api:tmdb`  -> TmdbSearchService
2. In `:data:model`, define new data type
```kotlin
sealed class SearchResult {
    data class Video(val item videoThumbnail: VideoThumbnail)
    // later we can add other search result types
    // data class Actor(val item actor) 
}
```
4. Then new `:data:tmdb-search` module, in here we return list of a new model called
so we need a new mapper to map the tmdb search result to our custom `SearchResult` data type
then we will have: 
```kotlin
interface TmdbSearchRepository {
    fun searchStream(query: String): Flow<PagingData<SearchResult>>
}
```
5. Then new `:domain:tmdb:search` in domain and so on

Let me know if you have any questions.
