### ISSUE TITLE
[FR]: Search tv shows by keyword

### ISSUE THREAD

**Issue by hadi-norouzi** [moallemi/Film-Time#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Related app

All - Android

### Describe the problem

As a user, I want to have a search functionality in the series section or somewhere in the app.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by moallemi** [comment]
We decided to have only one search screen [(#64 )](https://github.com/moallemi/Film-Time/issues/64#issuecomment-2118905248)
