### ISSUE TITLE
Recent viewed section

### ISSUE THREAD

**Issue by hadi-norouzi** [moallemi/Film-Time#9]
I want to have a section in HomeScreen that shows recently played movies or shows and I will be able to resume them.

**Comment by moallemi** [comment]
Before that, we need to have a source for streaming. Do you want to mock the streaming feature (as it is now) and implement this feature?

And, How do you want to store recently played movies and shows?

I guess we have 3 options:
1- Sync with Trakt
2- Sync with a stream provider (Using their API)
3- Sync locally in SP or DB

**Comment by hadi-norouzi** [comment]
I think the mock stream is enough for now, and I think about saving it locally, a table of the combination of movie ID and the elapsed time of the movie.

**Comment by moallemi** [comment]
Do you want to add this feature as part of hacktoberfest challenge or you are willing to contribute to this project?

if it is hacktoberfest, we can discuss on some issues toward hacktoberfest goals, otherwise I should explain what I am thinking for the feature of this project and then we pick some issues.

**Comment by hadi-norouzi** [comment]
Actually both.
But my goal is to contribute.
I can work on what you think is more important right now.

**Comment by moallemi** [comment]
Alright, I'll add some short-term and long-term user stories by tomorrow.

**Comment by moallemi** [comment]
Dear @hadi-norouzi, I added a few user stories to pick from.

#12 #13 #14 #15 #16, you can spilt each story to relevant PRs and please let others know if you started to work on any story.

And one more thing. Do not hesitate to suggest any other changes or features.
